version: '3.8'

services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: file-upload
  admainer:
    image: adminer:4.7.8-standalone
    restart: always
    ports:
      - "8088:8088"
    depends_on:
      - db
  web:
    build: .
    restart: always
    privileged: true
    ports:
      - "8080:8080"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1[::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    command: bash -c "python manage.py collectstatic --noinput 
             && python manage.py makemigrations
             && python manage.py migrate 
             && gunicorn fileupload.wsgi -b 0.0.0.0:8080"
    volumes:
      - static_volume:/home/app/web/staticfiles
    depends_on:
        - db
        - redis
#  redis:
#    image: redis:latest
#    ports:
#      - "6379:6379"  # Порт Redis

#  celery:
#      image: celery:latest
#      command: celery -A --app=fileupload worker -l info
#      depends_on:
#        - redis
  celery:
    build: .
    command: celery -A fileupload worker -l info
    depends_on:
      - web
      - redis
  redis:
    image: "redis:alpine"

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - "8000:80"
    depends_on:
       - web
volumes:
  static_volume: