# Generated by Django 4.2.5 on 2023-09-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='processed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
